##======================================================================================================================
##  SPY - C++ Informations Broker
##  Copyright : SPY Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: SPY Integration Tests
on:
  push:
    branches:
      - main

concurrency:
  group: spy-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    uses: jfalcou/copacabana/.github/workflows/integration.yml@468da45ac73a026a4bca4510840ebe635aa66c2c # v6
    with:
      project: spy
      cxx-compiler: clang++
      cxx-flags: -std=c++20
