##======================================================================================================================
##  SPY - C++ Informations Broker
##  Copyright : SPY Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: SPY Integration Tests
on:
  push:
    branches:
      - main

concurrency:
  group: spy-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    uses: jfalcou/copacabana/.github/workflows/integration.yml@17df3f26736d3a0ecc231a3b951f548dcbc09c45 # v2
    with:
      project: spy
      cxx-compiler: clang++
      cxx-flags: -std=c++20
