##======================================================================================================================
##  SPY - C++ Informations Broker
##  Copyright : SPY Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: SPY Linux Tests
on:
  workflow_call:

jobs:
  linux:
    name: ${{ matrix.compiler.name }} (${{ matrix.options }})
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jfalcou/compilers:${{ matrix.compiler.image }}
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { name: "gcc"          , preset: "gcc"             , image: "v10" }
          - { name: "clang"        , preset: "clang"           , image: "v10" }
          - { name: "aarch64"      , preset: "gcc-aarch64"     , image: "v10" }
          - { name: "aarch64 sve"  , preset: "gcc-aarch64-sve" , image: "v10" }
          - { name: "aarch64 sve2" , preset: "gcc-aarch64-sve2", image: "v10" }
          - { name: "ppc64"        , preset: "gcc-ppc64"       , image: "v10" }
          - { name: "wasm"         , preset: "wasm"            , image: "v10" }
          - { name: "rvv128"       , preset: "rvv128"          , image: "v10" }
          - { name: "icpx"         , preset: "icpx"            , image: "sycl-v1", setup: "/opt/intel/oneapi/setvars.sh" }
          - { name: "icpx sycl"    , preset: "icpx-sycl"       , image: "sycl-v1", setup: "/opt/intel/oneapi/setvars.sh" }

        options: [Debug, Release]

    steps:
      - name: Fetch current branch
        uses: actions/checkout@v7

      - name: Configure CMake and Build
        uses: jfalcou/copacabana/.github/actions/config@bdd4698a6b7653510904e7e408298c574591af69 # v5
        with:
          config: ${{ matrix.options }}
          preset: ${{ matrix.compiler.preset }}
          setup-script: ${{ matrix.compiler.setup }}

      - name: Run Unit Tests
        uses: jfalcou/copacabana/.github/actions/test@bdd4698a6b7653510904e7e408298c574591af69 # v5
        with:
          config: ${{ matrix.options }}
          preset: ${{ matrix.compiler.preset }}
