##======================================================================================================================
##  SPY - C++ Informations Broker
##  Copyright : SPY Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: SPY MacOS Tests
on:
  workflow_call:

jobs:
  macos:
    name: clang (${{ matrix.options }})
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        options: [Debug, Release]

    steps:
      - name: Fetch current branch
        uses: actions/checkout@v7

      - name: Configure CMake and Build
        uses: jfalcou/copacabana/.github/actions/config@468da45ac73a026a4bca4510840ebe635aa66c2c # v6
        with:
          config: ${{ matrix.options }}
          preset: clang-macos

      - name: Run Unit Tests
        uses: jfalcou/copacabana/.github/actions/test@468da45ac73a026a4bca4510840ebe635aa66c2c # v6
        with:
          config: ${{ matrix.options }}
          preset: clang-macos
