##======================================================================================================================
##  SPY - C++ Informations Broker
##  Copyright : SPY Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: SPY Nvidia Tests
on:
  workflow_call:

jobs:
  nvidia:
    name: ${{ matrix.compiler.name }} (${{ matrix.options }})
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { name: "nvcc"      , preset: "nvcc"       }
          - { name: "clang-cuda", preset: "clang-cuda" }

        options: [Debug, Release]

    steps:
      - name: Fetch current branch
        uses: actions/checkout@v7

      - name: Configure CMake and Build
        uses: ./.github/actions/config
        with:
          config: ${{ matrix.options }}
          preset: ${{ matrix.compiler.preset }}

      - name: Run Unit Tests
        uses: ./.github/actions/test
        with:
          config: ${{ matrix.options }}
          preset: ${{ matrix.compiler.preset }}
