##======================================================================================================================
##  SPY - C++ Informations Broker
##  Copyright : SPY Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: SPY Standalone Generation
on:
  push:
    branches:
      - main

jobs:
  package-standalone:
    permissions:
      contents: write
      pull-requests: write
    uses: jfalcou/copacabana/.github/workflows/package-standalone.yml@3337f916bb581d0829909976773f7a2ee827a25c # v4
    with:
      project: spy
