##======================================================================================================================
##  SPY - C++ Informations Broker
##  Copyright : SPY Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: SPY Standalone Generation
on:
  push:
    branches:
      - main

jobs:
  package-standalone:
    permissions:
      contents: write
      pull-requests: write
    uses: jfalcou/copacabana/.github/workflows/package-standalone.yml@bdd4698a6b7653510904e7e408298c574591af69 # v5
    with:
      project: spy
