##======================================================================================================================
##  SPY - C++ Informations Broker
##  Copyright : SPY Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: SPY Documentation Generation
on:
  push:
    branches:
      - main

jobs:
  package-standalone:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jfalcou/compilers:v9
    strategy:
      fail-fast: false
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v4.1.1

      - name: Configure SPY
        run: |
          mkdir build && cd build
          cmake .. -G Ninja -DSPY_BUILD_TEST=OFF -DSPY_BUILD_DOCUMENTATION=OFF

      - name: Generate standalone SPY header
        run: |
          cd build && ninja spy-standalone

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: spy-standalone-header
          path: build/spy-standalone.hpp
