##======================================================================================================================
##  SPY - C++ Informations Broker
##  Copyright : SPY Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: SPY Documentation Generation
on:
  push:
    branches:
      - main

jobs:
  package-standalone:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    container:
      image: ghcr.io/jfalcou/compilers:v9
    strategy:
      fail-fast: false
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v4.1.1

      - name: Configure SPY
        run: |
          git config --global --add safe.directory /__w/spy/spy
          mkdir build && cd build
          cmake .. -G Ninja -DSPY_BUILD_TEST=OFF -DSPY_BUILD_DOCUMENTATION=OFF

      - name: Generate standalone SPY header
        run: |
          cd build && ninja spy-standalone

      - name: Update standalone branch
        run: |
          git fetch origin
          git config --global user.email "spy@nowhere.com"
          git config --global user.name "SPY Standalone Generator"
          git checkout standalone
          cp build/spy.hpp spy.hpp
          git add spy.hpp
          git commit -m "Latest SPY standalone"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}