##======================================================================================================================
##  SPY - C++ Informations Broker
##  Copyright : SPY Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: SPY Standalone Generation
on:
  push:
    branches:
      - main

jobs:
  package-standalone:
    permissions:
      contents: write
      pull-requests: write
    uses: jfalcou/copacabana/.github/workflows/package-standalone.yml@44053e713b1b57329ccbcbb8878c839024bf19ee # v8
    with:
      project: spy
