##======================================================================================================================
##  SPY - C++ Informations Broker
##  Copyright : SPY Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: SPY Sanitizers
on:
  workflow_call:

jobs:
  sanitizers:
    name: ${{ matrix.compiler.name }} (ASan+UBSan)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jfalcou/compilers:v10
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { name: "gcc"  , preset: "gcc-sanitize"   }
          - { name: "clang", preset: "clang-sanitize" }

    steps:
      - name: Fetch current branch
        uses: actions/checkout@v7

      - name: Configure CMake and Build
        uses: ./.github/actions/config
        with:
          config: Debug
          preset: ${{ matrix.compiler.preset }}

      - name: Run Unit Tests
        uses: ./.github/actions/test
        with:
          config: Debug
          preset: ${{ matrix.compiler.preset }}
