##======================================================================================================================
##  SPY - C++ Informations Broker
##  Copyright : SPY Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: SPY Windows Tests
on:
  workflow_call:

jobs:
  windows:
    name: ${{ matrix.compiler.name }} (${{ matrix.options }})
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { name: "msvc"    , preset: "msvc"    }
          - { name: "clang-cl", preset: "clangcl" }

        options: [Debug, Release]

    steps:
      - name: Fetch current branch
        uses: actions/checkout@v7

      - name: Configure CMake and Build
        uses: jfalcou/copacabana/.github/actions/config@bdd4698a6b7653510904e7e408298c574591af69 # v5
        with:
          config: ${{ matrix.options }}
          preset: ${{ matrix.compiler.preset }}

      - name: Run Unit Tests
        uses: jfalcou/copacabana/.github/actions/test@bdd4698a6b7653510904e7e408298c574591af69 # v5
        with:
          config: ${{ matrix.options }}
          preset: ${{ matrix.compiler.preset }}
